POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username":"user","password":"1234"}
###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username":"user","password":"1234","email":"user@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token cb7ef30730f11146d28d090c3dc48de239073e43

###

POST http://127.0.0.1:8000/categories/create/
Content-Type: application/json

{
    "name": "Electronics",
    "desc": "Devices and gadgets"
}

###

GET http://127.0.0.1:8000/categories/view/
Content-Type: application/json

###

POST http://127.0.0.1:8000/products/create/
Content-Type: application/json

{
    "name": "Smartphone",
    "description": "Latest model with 5G support",
    "price": 699.99,
    "stock": 50,
    "category": 1
}

###

GET http://127.0.0.1:8000/products/view/
Content-Type: application/json


###

POST http://127.0.0.1:8000/blogs/
Content-Type: application/json

{
    "title": "My First Blog",
    "content": "This is the content of my first blog."
}

###

GET http://127.0.0.1:8000/blogs/
Content-Type: application/json