
### Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username":"user","password":"1234"}

### View cart
GET http://127.0.0.1:8000/cart/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

### Add product to cart
POST http://127.0.0.1:8000/cart/add/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

{
    "product_id": 4,
    "quantity": 3
}

### Delete item from cart
POST http://127.0.0.1:8000/cart/delete/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

{
    "product_id": 3,
    "quantity": 1
}

### View Cart
GET http://127.0.0.1:8000/cart/view/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

### Checkout cart
POST http://127.0.0.1:8000/orders/checkout/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

### View orders
GET http://127.0.0.1:8000/orders/view/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

### Payment status update
PUT http://127.0.0.1:8000/payment/6/update/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

{
    "status": "SUCCESS"
}