### Create category

POST http://127.0.0.1:8000/categories/create/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

{
    "name": "Electronics",
    "desc": "Devices and gadgets"
}

### Create product

POST http://127.0.0.1:8000/products/create/
Content-Type: application/json
Authorization: Token 5eab30320254a8f22a7ab054baa05e9f6bd14549

{
    "name": "Smart watch",
    "description": "Watch tells time",
    "price": 100.99,
    "stock": 10,
    "category": 1
}

### View all Products

GET http://127.0.0.1:8000/products/view/
Content-Type: application/json
Authorization: Token 62c846ed019772c41f3b6190ceaa9dc9694bcc2d

### View Product description

GET http://127.0.0.1:8000/products/view/3/
Content-Type: application/json


### Stock-up product

PUT http://127.0.0.1:8000/products/4/stockup/
Content-Type: application/json

{
    "quantity": 100
}

### Delete product

DELETE http://127.0.0.1:8000/products/2/delete/
Content-Type: application/json

